name: yaml-file for unittests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
        
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - name: Install Angular program dependencies, Angular global CLI + ng build
        run: cd frontend && npm i -g @angular/cli && npm i && ng serve & echo "NG_PID=$!" >> $GITHUB_ENV

      - name: Build test code and install playwright test browser
        run: cd test && sleep 60 && dotnet build && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Build and run Web API + getting process ID for shutting down later
        run: cd api && dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
        env:
          pgconn: ${{secrets.PGCONN}}
      
      - name: run all tests (But first sleep for 60 seconds)
        run: cd test && sleep 30 && dotnet build && bin/Debug/net8.0/playwright.ps1 install && dotnet test
        env:
          pgconn: ${{secrets.PGCONN}}
          frompass: ${{secrets.FROMPASS}}
          fromemail: ${{secrets.FROMEMAIL}}

      - name: Shutdown the api && frontend
        run: kill $API_PID && kill $FRONTEND_PID
